# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-02 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20171119_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='content_uk',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_detail_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_detail_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_detail_postcode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_detail_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_detail_street',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_detail_first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_detail_last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_detail_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_detail_postcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='_meta_title_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='content_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='name_uk',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='option1_uk',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='option2_uk',
        ),
    ]
