# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-14 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20180202_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_detail_delivery',
            field=models.CharField(choices=[(0, 'Nova Poshta'), (1, 'Self-checkout')], default=0, max_length=32, verbose_name='Type of delivery'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_detail_payment',
            field=models.CharField(choices=[(0, 'Cash on delivery'), (1, 'Bank transaction')], default=1, max_length=32, verbose_name='Type of payment'),
        ),
    ]
