# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-15 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20180214_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_detail_np',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='NovaPoshta department'),
        ),
    ]
